server:
  port: 8095
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realestateDB
    username: root
    password: GtaHesoyam123!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: easemakers.cosy@gmail.com
    password: wkfa dwgr knnh ecqv
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 31536000000 # 1 an en millisecondes
  image:

    remoteUrl: http://37.187.181.122:8095/api/v1/images/
    localUrl: http://127.0.0.1:8095/api/v1/images/
    path:
      local: file:C:/images/
      remote: file:/home/ubuntu/images/



logging:
  level:
    org.springframework.security: DEBUG

